# ---- Avocado Theme ---- #

[window]
# window padding {px}
padding.x = 12
padding.y = 12

[font]
size = 12.0

[colors]
[colors.primary]
# background and foreground
background = "#000000"
foreground = "#B5E631"
# slightly darker / desaturated foreground for "dim" text
dim_foreground = "#99A91D"

[colors.cursor]
text = "#000000"          # use terminal background for contrast
cursor = "#B5E631"        # primary accent

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#B5E631"

[colors.selection]
text = "CellForeground"
background = "#160000"    # secondary background

